services:
  file-service:
    image: oakcan/file-service:latest
    container_name: oakcan-file-service-test
    ports:
      - "9004:8081"
    environment:
      - SPRING_ACTIVE_PROFILE=test
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      gateway:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - oakcan-test-network
networks:
  oakcan-test-network:
    external: true
