spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  instance:
    hostname: discovery-server
  client:
    register-with-eureka: false
    fetch-registry: false
# actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info