services:
  discovery-server:
    image: oakcan/discovery-server:0.0.1-SNAPSHOT
    container_name: oakcan-discovery-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
  config-server:
    image: oakcan/config-server:0.0.1-SNAPSHOT
    container_name: oakcan-config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - "8071:8071"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
  gateway:
    image: oakcan/gateway:0.0.1-SNAPSHOT
    container_name: oakcan-gateway
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8084/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
  file-service:
    image: oakcan/file-service:0.0.1-SNAPSHOT
    container_name: oakcan-file-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      gateway:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
  sync-service:
    image: oakcan/sync-service:0.0.1-SNAPSHOT
    container_name: oakcan-sync-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      gateway:
        condition: service_healthy
  user-service:
    image: oakcan/user-service:0.0.1-SNAPSHOT
    container_name: oakcan-user-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - TEST_DB_URL=jdbc:postgresql://user-test-db:5432/user-test-db
      - DEV_DB_URL=jdbc:postgresql://user-dev-db:5432/user-dev-db
      - TEST_MAIL_HOST=mailhog
      - DEV_MAIL_HOST=mailhog
      - TEST_MAIL_PORT=1025
      - DEV_MAIL_PORT=1025
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      gateway:
        condition: service_healthy
      mailhog:
        condition: service_healthy
      user-dev-db:
        condition: service_healthy

  client:
    image: oakcan/client:0.0.1-SNAPSHOT
    container_name: oakcan-client
    build:
      context: ./apps/web
    ports:
      - "3000:3000"
  docs:
    image: oakcan/docs:0.0.1-SNAPSHOT
    container_name: oakcan-docs
    build:
      context: docs
    ports:
      - "8000:8000"