example:
  property: I AM THE DEFAULT
spring:
  application:
    name: sync-service
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
