spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config/file-service
            - classpath:/config/gateway
            - classpath:/config/sync-service
            - classpath:/config/user-service
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
      register-with-eureka: true
server:
  port: 8071