spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${FILE_DEV_DB_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
logging:
  level:
    com.bytebandit.file-service: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.boot.autoconfigure.security.servlet: DEBUG
    org.springframework.boot.autoconfigure.web.servlet.error: DEBUG
