example:
  property: I AM THE DEFAULT
spring:
  application:
    name: file-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 0
    baseline-on-migrate: true
    validate-on-migrate: true
    table: file_service_flyway_schema_history
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
springdoc:
  packagesToScan: com.bytebandit.fileservice.controller,com.bytebandit.fileservice.exception
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
