spring:
  jpa:
    show-sql: true
  sql:
    init:
      schema-locations: classpath:schema.sql
api:
  prefix: /api/v1/user
  host:
    uri: http://localhost:8084
client:
  host:
    uri: http://localhost:3000
