spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:${secrets.datasource.url}}
    username: ${DB_USERNAME:${secrets.datasource.username}}
    password: ${DB_PASSWORD:${secrets.datasource.password}}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:classpath:secrets.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mail:
    host: ${MAIL_HOST:${secrets.mail.host}}
    port: ${MAIL_PORT:${secrets.mail.port}}
    username: ${MAIL_USERNAME:${secrets.mail.username}}
    password: ${MAIL_PASSWORD:${secrets.mail.password}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
