spring:
  application:
    name: user-service
  datasource:
    url: ${secrets.datasource.url}
    username: ${secrets.datasource.username}
    password: ${secrets.datasource.password}
    driver-class-name: org.postgresql.Driver
  config:
    import: classpath:secrets.yml

server:
    port: 8083

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/