example:
  property: I AM THE DEFAULT
spring:
  application:
    name: gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 0
    baseline-on-migrate: true
    validate-on-migrate: false
    table: gateway_flyway_schema_history
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    registry-fetch-interval-seconds: 40
    fetch-registry: true
management:
  endpoint:
    web:
      exposure:
        include: health,info
springdoc:
  packagesToScan: com.bytebandit.gateway.controller
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    urls:
      - name: Gateway
        url: http://localhost:8084/v3/api-docs
      - name: User Service
        url: http://localhost:8083/api/v1/user/v3/api-docs
      - name: File Service
        url: http://localhost:8081/api/v1/file/v3/api-docs
