spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${USER_DEV_DB_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
cors:
  allowed_origins: ${CORS_ALLOWED_ORIGINS}
app:
  permitted:
    routes: /api/v1/auth/login,/api/v1/user/register,/api/v1/user/verify,/csrf,/test-csrf,/actuator/*
  access-token-expiration: 3600
  refresh-token-expiration: 86400
