example:
  property: I AM THE DEFAULT
spring:
  application:
    name: gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 0
    baseline-on-migrate: true
    validate-on-migrate: true
    table: gateway_flyway_schema_history
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    registry-fetch-interval-seconds: 40
    fetch-registry: true
management:
  endpoint:
    web:
      exposure:
        include: health,info
