name: Deploy Docs to Vercel
env:
    VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
    VERCEL_PROJECT_ID: ${{secrets.VERCEL_DOC_PROJECT_ID}}
on:
    push:
        branches:
            - '**'
        paths:
            - 'docs/**'
    pull_request:
        branches:
            - '**'
        paths:
            - 'docs/**'
jobs:
    deploy-docs:
        name: Deploy Docs to Vercel
        needs: test-docs
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4

            -   name: Set Up Python 3.9
                uses: actions/setup-python@v4
                with:
                    python-version: '3.9'

            -   name: Install MkDocs Dependencies
                working-directory: docs
                run: |
                    pip install -r requirements.txt

            -   name: Build MkDocs Site
                working-directory: docs
                run: |
                    mkdocs build

            -   name: Install Vercel CLI
                run: npm install -g vercel

            -   name: Determine environment
                id: vars
                run: |
                    if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
                        echo "ENVIRONMENT=production" >> $GITHUB_ENV
                        echo "DEPLOY_PROD=true" >> $GITHUB_ENV
                    else
                        echo "ENVIRONMENT=preview" >> $GITHUB_ENV
                        echo "DEPLOY_PROD=false" >> $GITHUB_ENV
                    fi
            -   name: Pull Vercel Environment Information
                run: vercel pull --yes --environment=${{ env.ENVIRONMENT }} --token=${{ secrets.VERCEL_TOKEN }}
            -   name: Deploy to Vercel
                working-directory: docs
                env:
                    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                run: |
                    cd site
                    if [[ "${{ env.DEPLOY_PROD }}" == "true" ]]; then
                        echo "Deploying to production (main branch)..."
                        vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
                    else
                        echo "Deploying to preview for branch: ${{ github.ref }}"
                        vercel deploy --token ${{ secrets.VERCEL_TOKEN }} --yes
                    fi