services:
  sync-service:
    image: oakcan/sync-service:latest
    container_name: oakcan-sync-service-test
    ports:
      - "9005:8082"
    environment:
      - SPRING_ACTIVE_PROFILE=test
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      gateway:
        condition: service_healthy
    networks:
      - oakcan-test-network
networks:
  oakcan-test-network:
    external: true
