version: '0.0.1-SNAPSHOT'
services:
  discovery:
    image: oakcan/discovery:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
  gateway:
    image: oakcan/gateway:0.0.1-SNAPSHOT
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    depends_on:
      - discovery