spring:
    application:
        name: gateway
    profiles:
        active: dev
server:
    port: 8084
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
logging:
    level:
      org:
        springframework:
            boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration: OFF