spring:
  application:
    name: gateway
  datasource:
    url: ${secrets.datasource.url}
    username: ${secrets.datasource.username}
    password: ${secrets.datasource.password}
    driver-class-name: org.postgresql.Driver
  config:
    import: classpath:secrets.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true