name: backend-linting
on:
  push:
    branches:
      - '*'
    paths:
      - 'apps/backend/**'
  pull_request:
    branches:
      - develop
      - main
      - develop-snapshot
    paths:
      - 'apps/backend/**'
jobs:
  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('apps/backend/pom.xml') }}

      - name: Run Checkstyle
        run: cd apps/backend && mvn checkstyle:check
