name: Linting

on:
  push:
    branches:
      - '*'
    paths:
      - 'apps/web/**'
      - 'apps/backend/**'
  pull_request:
    branches:
      - develop
      - main
      - develop-snapshot
    paths:
      - 'apps/web/**'
      - 'apps/backend/**'

jobs:
  backend-lint:
    runs-on: ubuntu-latest
    # Only run if there are changes in apps/backend/
    if: ${{ contains(github.event_name == 'push' && github.event.commits.*.modified, 'apps/backend/') || contains(github.event.pull_request.files.*.filename, 'apps/backend/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('apps/backend/pom.xml') }}

      - name: Run Checkstyle
        run: cd apps/backend && mvn checkstyle:check

  frontend-lint:
    runs-on: ubuntu-latest
    # Only run if there are changes in apps/web/
    if: ${{ contains(github.event_name == 'push' && github.event.commits.*.modified, 'apps/web/') || contains(github.event.pull_request.files.*.filename, 'apps/web/') }}
    defaults:
      run:
        working-directory: apps/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Check for ESLint errors
        if: ${{ failure() }}
        run: echo "ESLint failed!" && exit 1