name: Linting

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop
      - main
      - develop-snapshot
jobs:
  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('apps/backend/pom.xml') }}
      - name: Run Checkstyle
        run: cd apps/backend && mvn checkstyle:check
  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        working-directory: apps/web
        run: npm install
      - name: Run ESLint
        working-directory: apps/web
        run: npm run lint
      - name: Check for ESLint errors
        if: ${{ failure() }}
        run: echo "ESLint failed!" && exit 1